/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Telas.utilidades.JMoneyField;
import Telas.utilidades.TeclasPermitidasNumeros;
import model.dao.CategoriaDAO;
import model.dao.DescricaoprodutoDAO;
import model.dao.ProdutoDAO;
import sistemacontroleestoque.Categoria;
import sistemacontroleestoque.Descricaoproduto;
import sistemacontroleestoque.Produto;

/**
 *
 * @author usuario
 */
public class Adicionarproduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Adicionarproduto
     */
    
    private javax.swing.JDesktopPane areatra;
    
    public Adicionarproduto(javax.swing.JDesktopPane area) {
        areatra = area;
        initComponents();
        jTextField3.setDocument(new TeclasPermitidasNumeros());
        jTextField4.setDocument(new TeclasPermitidasNumeros());
        //jFormattedTextField3.setDocument(new TeclasPermitidasNumeros());
        preenchercategoria();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jButton1 = new javax.swing.JButton();
        jMoneyField1 = new Telas.utilidades.JMoneyField();
        jMoneyField2 = new Telas.utilidades.JMoneyField();

        setClosable(true);
        setTitle("Adicionar Produto");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Escolha um item>" }));
        jComboBox1.setToolTipText("");
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha um produto");

        jCheckBox1.setText("Novo produto");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jTextField1.setToolTipText("");
        jTextField1.setEnabled(false);

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Escolha um item>" }));
        jComboBox2.setToolTipText("");
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Escolha uma categoria");

        jTextField2.setEnabled(false);

        jCheckBox2.setText("Nova Categoria");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Quantidade Comprada");

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel4.setText("Quantidade Em estoque");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jLabel5.setText("Preço de compra");

        jLabel6.setText("Preço de Venda");

        jLabel7.setText("Data de validade");

        try {
            jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField3.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel7)
                                    .addComponent(jFormattedTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(jMoneyField1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(28, 28, 28)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField4)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel4))
                                        .addGap(0, 32, Short.MAX_VALUE))
                                    .addComponent(jMoneyField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(6, 6, 6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jTextField2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBox2)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(153, 153, 153)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addGap(10, 10, 10)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jMoneyField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMoneyField1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setBounds(0, 0, 405, 433);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        
        if(jCheckBox1.isSelected())
        {
            jTextField1.setText("Digite o nome do produto");
            jTextField1.enable(true);
            jComboBox1.enable(false);
        }
        else
        {
            jTextField1.setText("");
            jTextField1.enable(false);
            jComboBox1.enable(true);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        
        if(jCheckBox2.isSelected())
        {
            jComboBox1.removeAllItems();
            jComboBox1.addItem("<Escolha um item>");
            jTextField2.setText("Digite a nova categoria");
            jTextField2.enable(true);
            jComboBox2.enable(false);
        }
        else
        {
            jTextField2.setText("");
            jTextField2.enable(false);
            jComboBox2.enable(true);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed

        int i = jComboBox2.getSelectedIndex();
        if(jComboBox2.getItemAt(i).equals("<Escolha um item>") || (jTextField2.getText().equals("") && jCheckBox2.isSelected()))
        {
            jTextField1.enable(false);
            jComboBox1.enable(false);
        }
        else
        {
            jComboBox1.enable(true);
            preencherdescricao(jComboBox2.getItemAt(i));
        }
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if(campospreenchidos() == 0)
        {
            Produto produto = new Produto();
            produto.setCategoria(verificacategoria());
            produto.setDescricao(verificadescricao());
            
            produto.setQuantidadecomprada(Integer.parseInt((jTextField3.getText())));
            produto.setQuantidadeestoque(Integer.parseInt(jTextField4.getText()));
            produto.setPrecocompra(Float.parseFloat(jMoneyField1.getTextFloat()));
            produto.setPrecovenda(Float.parseFloat(jMoneyField2.getTextFloat()));
            produto.setDatavalidade(jFormattedTextField3.getText().replace("/", "-"));
            
            ProdutoDAO dao = new ProdutoDAO();
            dao.save(produto);
            
            MensagemSucesso mensagem = new MensagemSucesso("Produto Adicionado com sucesso");
            areatra.add(mensagem);
            mensagem.setVisible(true);
        }
        else
        {
            System.out.println("Erro!");
            System.out.println(campospreenchidos());
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private Telas.utilidades.JMoneyField jMoneyField1;
    private Telas.utilidades.JMoneyField jMoneyField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables

    private void preencherdescricao(String categoria) {
        jComboBox1.removeAllItems();
        jComboBox1.addItem("<Escolha um item>");
        ProdutoDAO dao = new ProdutoDAO();
        for(Produto p : dao.Select())
        {
            if(p.getCategoria().getDescricao().equals(categoria))
            {
                jComboBox1.addItem(p.getDescricao().getDescricao());
            }
        }
    }

    private void preenchercategoria() {
        CategoriaDAO dao = new CategoriaDAO();
        for(Categoria c : dao.Select())
        {
            jComboBox2.addItem(c.getDescricao());
        }
    }
    
    private int campospreenchidos()
    {
        int indexbox1 = jComboBox1.getSelectedIndex();
        int indexbox2 = jComboBox2.getSelectedIndex();
        if(((jComboBox2.getItemAt(indexbox2).equals("<Escolha um item>") && !jCheckBox2.isSelected()) || (jCheckBox2.isSelected() && jTextField2.getText().equals(""))))
        {
            return 1;
        }
        
        if(((jComboBox1.getItemAt(indexbox1).equals("<Escolha um item>") && !jCheckBox1.isSelected()) || (jCheckBox1.isSelected() && jTextField1.getText().equals(""))))
        {
            return 2;
        }
        
        if(jTextField3.getText().equals(""))
        {
            return 3;
        }
        
        if(jTextField4.getText().equals(""))
        {
            return 4;
        }
        
        if(jMoneyField1.getText().equals(""))
        {
            return 5;
        }
        
        if(jMoneyField2.getText().equals(""))
        {
            return 6;
        }
        
        if(jFormattedTextField3.getText().equals(""))
        {
            return 7;
        }
        return 0;
    }
    
    private Categoria verificacategoria()
    {
        Categoria cat = new Categoria();
        if(jCheckBox2.isSelected())
        {
            CategoriaDAO dao = new CategoriaDAO();
            cat.setDescricao(jTextField2.getText());
            dao.save(cat);
        }
        else
        {
            cat.setDescricao(jComboBox2.getItemAt(jComboBox2.getSelectedIndex()));
        }
            
        CategoriaDAO dao = new CategoriaDAO();
        for(Categoria c : dao.Select())
        {
            if(c.getDescricao().equals(cat.getDescricao()))
            {
                cat.setId(c.getId());
                break;
            }
        }
        return cat;
    }
    
    private Descricaoproduto verificadescricao()
    {
        Descricaoproduto des = new Descricaoproduto();
        
        if(jCheckBox1.isSelected())
        {
            DescricaoprodutoDAO dao = new DescricaoprodutoDAO();
            des.setDescricao(jTextField1.getText());
            dao.save(des);
        }
        else
        {
            des.setDescricao(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
        }
        
        DescricaoprodutoDAO dao = new DescricaoprodutoDAO();
        
        for(Descricaoproduto d : dao.Select())
        {
            if(d.getDescricao().equals(des.getDescricao()))
            {
                des.setId(d.getId());
                break;
            }
        }
        return des;
    }
}
