/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Telas;

import Telas.utilidades.TeclasPermitidasNumeros;
import java.util.ArrayList;
import java.util.List;
import model.dao.CategoriaDAO;
import model.dao.DescricaoprodutoDAO;
import model.dao.ProdutoDAO;
import sistemacontroleestoque.Categoria;
import sistemacontroleestoque.Descricaoproduto;
import sistemacontroleestoque.Produto;

/**
 *
 * @author usuario
 */
public class Alterarproduto extends javax.swing.JInternalFrame {

    /**
     * Creates new form Alterarproduto
     */
    private javax.swing.JDesktopPane areatra;
    
    int IDselecionado; //erro se a pessoa alterar o campo ID e clicar em alterar
    
    public Alterarproduto(javax.swing.JDesktopPane area) {
        areatra = area;
        initComponents();
        jTextID.setDocument(new TeclasPermitidasNumeros());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField2 = new javax.swing.JTextField();
        jCheckBox1 = new javax.swing.JCheckBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jTextField3 = new javax.swing.JTextField();
        jCheckBox2 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jMoneyField1 = new Telas.utilidades.JMoneyField();
        jLabel7 = new javax.swing.JLabel();
        jMoneyField2 = new Telas.utilidades.JMoneyField();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jButton3 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        setClosable(true);
        setTitle("Alterar Produto");

        jLabel1.setText("ID");

        jTextID.setHorizontalAlignment(javax.swing.JTextField.RIGHT);

        jButton1.setText("Pesquisar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Escolha um Item>" }));
        jComboBox1.setEnabled(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField2.setEnabled(false);

        jCheckBox1.setText("Nova Categoria");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel2.setText("Categoria");

        jLabel3.setText("Produto");

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<Escolha um Item>" }));
        jComboBox2.setEnabled(false);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        jTextField3.setEnabled(false);

        jCheckBox2.setText("Novo Produto");
        jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox2ActionPerformed(evt);
            }
        });

        jLabel4.setText("Quantidade Comprada");

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField4.setEnabled(false);

        jLabel5.setText("Quantidade em Estoque");

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextField5.setEnabled(false);

        jLabel6.setText("Preço de Compra");

        jMoneyField1.setEnabled(false);

        jLabel7.setText("Preço de Venda");

        jMoneyField2.setEnabled(false);

        jLabel8.setText("Data de Validade");

        try {
            jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####/##/##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextField1.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jFormattedTextField1.setEnabled(false);

        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 43, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCheckBox1))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 268, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jCheckBox2))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(68, 68, 68)
                                .addComponent(jLabel5))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(98, 98, 98)
                                .addComponent(jLabel7)))
                        .addGap(0, 6, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 189, Short.MAX_VALUE)
                            .addComponent(jMoneyField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextField4, javax.swing.GroupLayout.Alignment.LEADING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField5)
                            .addComponent(jMoneyField2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(jLabel8)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(146, 146, 146)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMoneyField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMoneyField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addContainerGap(24, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String num = jTextID.getText();
        
        if(!num.equals(""))
        {
            List<Produto> produtos = new ArrayList<>();
        
            ProdutoDAO dao = new ProdutoDAO();
            produtos = dao.Select(num);
        
            if(produtos.size() == 1)
            {
                IDselecionado = Integer.parseInt(num);
                int idcategoria;
                idcategoria = preenchecategoria(produtos);
                
                preenchedescricao(produtos, idcategoria);
                
                jTextField4.enable(true);
                jTextField4.setText(Integer.toString(produtos.get(0).getQuantidadecomprada()));
                
                jTextField5.enable(true);
                jTextField5.setText(Integer.toString(produtos.get(0).getQuantidadeestoque()));
                
                jMoneyField1.enable(true);
                jMoneyField1.setText(Float.toString(produtos.get(0).getPrecocompra()));
                
                jMoneyField2.enable(true);
                jMoneyField2.setText(Float.toString(produtos.get(0).getPrecovenda()));
                
                jFormattedTextField1.enable(true);
                jFormattedTextField1.setText(produtos.get(0).getDatavalidade().replace("-", "/"));
                
            }
            else
            {
                Mensagemcampoincompleto mensagem = new Mensagemcampoincompleto("Produto Inexistente");
                areatra.add(mensagem);
                mensagem.setVisible(true);
            }
        }
        else
        {
                Mensagemcampoincompleto mensagem = new Mensagemcampoincompleto("Digite um ID");
                areatra.add(mensagem);
                mensagem.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        if(jCheckBox1.isSelected())
        {
            jComboBox1.enable(false);
            jTextField2.enable(true);
        }
        else
        {
            jComboBox1.enable(true);
            jTextField2.enable(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox2ActionPerformed
        if(jCheckBox2.isSelected())
        {
            jComboBox2.enable(false);
            jTextField3.enable(true);
        }
        else
        {
            jComboBox2.enable(true);
            jTextField3.enable(false);
        }
    }//GEN-LAST:event_jCheckBox2ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String Categoria = jComboBox1.getItemAt(jComboBox1.getSelectedIndex());
        
        String nome = jComboBox2.getItemAt(0);
        jComboBox2.removeAllItems();
        jComboBox2.addItem(nome);
        
        ProdutoDAO dao = new ProdutoDAO();
        for(Produto p : dao.Select())
        {
            if(p.getCategoria().getDescricao().equals(Categoria) && !p.getDescricao().getDescricao().equals(nome))
            {
                jComboBox2.addItem(p.getDescricao().getDescricao());
            }
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        int erronum = campospreenchidos();
        if(erronum == 0)
        {
            Produto produto = new Produto();
            produto.setCategoria(verificacategoria());
            produto.setDescricao(verificadescricao());
            
            produto.setQuantidadecomprada(Integer.parseInt((jTextField4.getText())));
            produto.setQuantidadeestoque(Integer.parseInt(jTextField5.getText()));
            produto.setPrecocompra(Float.parseFloat(jMoneyField1.getTextFloat()));
            produto.setPrecovenda(Float.parseFloat(jMoneyField2.getTextFloat()));
            produto.setDatavalidade(jFormattedTextField1.getText().replace("/", "-"));
            
            produto.setId(IDselecionado);
            
            ProdutoDAO dao = new ProdutoDAO();
            dao.update(produto);
            
            MensagemSucesso mensagem = new MensagemSucesso("Produto Alterado com sucesso");
            areatra.add(mensagem);
            mensagem.setVisible(true);
        }
        else
        {
            String text;
            if(erronum == 1)
            {
                text = "Insira a categoria";
            }
            else
            {
                if(erronum == 2)
                {
                    text = "Insira o nome do produto";
                }
                else
                {
                    if(erronum == 3)
                    {
                        text = "Insira a Quantidade Comprada";
                    }
                    else
                    {
                        if(erronum == 4)
                        {
                            text = "Insira a Quantidade em Estoque";
                        }
                        else
                        {
                            if(erronum == 5)
                            {
                                text = "Insira o Preço de compra";
                            }
                            else
                            {
                                if(erronum == 6)
                                {
                                    text = "Insira o Preço de Venda";
                                }
                                else
                                {
                                    text = "Insira a data";
                                }
                            }
                        }
                    }
                }
            }
            Mensagemcampoincompleto mensagem = new Mensagemcampoincompleto(text);
            areatra.add(mensagem);
            mensagem.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private Telas.utilidades.JMoneyField jMoneyField1;
    private Telas.utilidades.JMoneyField jMoneyField2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextID;
    // End of variables declaration//GEN-END:variables
    
    public int preenchecategoria(List<Produto> produtos)
    {
        int idcategoria = 0;
        jComboBox1.enable(true);
        jComboBox1.removeAllItems();
        jComboBox1.addItem(produtos.get(0).getCategoria().getDescricao());
        CategoriaDAO cat = new CategoriaDAO();
        for(Categoria c : cat.Select())
        {
            if(!produtos.get(0).getCategoria().getDescricao().equals(c.getDescricao()))
            {
                        jComboBox1.addItem(c.getDescricao());
            }
            else
            {
                idcategoria = produtos.get(0).getCategoria().getId();
            }
        }
        return idcategoria;
    }
    
    public void preenchedescricao(List<Produto> produtos, int idcategoria)
    {
        String produtonome = produtos.get(0).getDescricao().getDescricao();
        jComboBox2.enable(true);
        jComboBox2.removeAllItems();
        jComboBox2.addItem(produtonome);
        
        ProdutoDAO dao = new ProdutoDAO();
        for(Produto p : dao.Select())
        {
            if(p.getCategoria().getId() == idcategoria && !p.getDescricao().getDescricao().equals(produtonome))
            {
                jComboBox2.addItem(p.getDescricao().getDescricao());
            }
        }
    }
    
        private int campospreenchidos()
    {
        int indexbox1 = jComboBox1.getSelectedIndex();
        int indexbox2 = jComboBox2.getSelectedIndex();
        if(((jComboBox1.getItemAt(indexbox1).equals("<Escolha um item>") && !jCheckBox1.isSelected()) || (jCheckBox1.isSelected() && jTextField2.getText().equals(""))))
        {
            return 1;
        }
        
        if(((jComboBox2.getItemAt(indexbox2).equals("<Escolha um item>") && !jCheckBox2.isSelected()) || (jCheckBox2.isSelected() && jTextField3.getText().equals(""))))
        {
            return 2;
        }
        
        if(jTextField4.getText().equals(""))
        {
            return 3;
        }
        
        if(jTextField5.getText().equals(""))
        {
            return 4;
        }
        
        if(jMoneyField1.getText().equals(""))
        {
            return 5;
        }
        
        if(jMoneyField2.getText().equals(""))
        {
            return 6;
        }
        
        if(jFormattedTextField1.getText().equals("    /  /  "))
        {
            return 7;
        }
        return 0;
    }
        
    private Categoria verificacategoria()
    {
        Categoria cat = new Categoria();
        if(jCheckBox1.isSelected())
        {
            CategoriaDAO dao = new CategoriaDAO();
            cat.setDescricao(jTextField2.getText());
            dao.save(cat);
        }
        else
        {
            cat.setDescricao(jComboBox1.getItemAt(jComboBox1.getSelectedIndex()));
        }
            
        CategoriaDAO dao = new CategoriaDAO();
        for(Categoria c : dao.Select())
        {
            if(c.getDescricao().equals(cat.getDescricao()))
            {
                cat.setId(c.getId());
                break;
            }
        }
        return cat;
    }
    
    private Descricaoproduto verificadescricao()
    {
        Descricaoproduto des = new Descricaoproduto();
        
        if(jCheckBox2.isSelected())
        {
            DescricaoprodutoDAO dao = new DescricaoprodutoDAO();
            des.setDescricao(jTextField3.getText());
            dao.save(des);
        }
        else
        {
            des.setDescricao(jComboBox2.getItemAt(jComboBox2.getSelectedIndex()));
        }
        
        DescricaoprodutoDAO dao = new DescricaoprodutoDAO();
        
        for(Descricaoproduto d : dao.Select())
        {
            if(d.getDescricao().equals(des.getDescricao()))
            {
                des.setId(d.getId());
                break;
            }
        }
        return des;
    }

}
